import { Collection } from "./types";

export const COLLECTIONS: Collection[] = [
  {
    id: "distrito-zinc-natural",
    name: "Distrito Zinc Natural 48x102",
    category: "Metal Look",
    finish: "Matte",
    formats: ["120×260cm"],
    specs: "Smooth Matte · 120×260 cm",
    origin: "Spain",
    veiningStyle: "Oxidized zinc teal green with rich mineral texture",
    description: "An architectural marvel. Striking, organic turquoise oxide layers interlock with cold zinc minerals to create a vibrant, weathered slate style.",
    backgroundGradient: "linear-gradient(135deg, #0e302e 0%, #1f423d 30%, #304e46 50%, #152c28 80%, #0c1a18 100%)",
    colors: ["Blue", "Grey"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Smooth Matte",
    colorGroup: "Blue and Greens",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "5.6 mm",
    visualLook: "Metal & Oxid Look",
    specificMaterialStyle: "Metal",
    productPhotoUrl: "https://media.grespania.com/productos/distrito_120x120_zinc_pza1_web_list.webp"
  },
  {
    id: "distrito-aluminio-natural",
    name: "Distrito Aluminio Natural 48x102",
    category: "Metal Look",
    finish: "Matte",
    formats: ["120×260cm"],
    specs: "Smooth Matte · 120×260 cm",
    origin: "Spain",
    veiningStyle: "Brushed aluminum silver grey with subtle oxid inclusions",
    description: "Cold-rolled industrial elegance. Features soft troweled silver dust accents and raw industrial alloy texturing.",
    backgroundGradient: "linear-gradient(135deg, #3a3d40 0%, #5c6266 30%, #4c5054 50%, #2f3133 80%, #1d1e1f 100%)",
    colors: ["Grey"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Smooth Matte",
    colorGroup: "Dark Grey",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "5.6 mm",
    visualLook: "Metal & Oxid Look",
    specificMaterialStyle: "Metal",
    productPhotoUrl: "https://media.grespania.com/productos/distrito_120x120_aluminio_web_list.webp"
  },
  {
    id: "distrito-iron-natural",
    name: "Distrito Iron Natural 48x102",
    category: "Metal Look",
    finish: "Matte",
    formats: ["120×260cm"],
    specs: "Smooth Matte · 120×260 cm",
    origin: "Spain",
    veiningStyle: "Deep graphite and cast-iron black with soft matte luster",
    description: "Deep oxide black metallic plate design. Unyielding structural aesthetic for high-impact commercial lobbies and private lofts.",
    backgroundGradient: "linear-gradient(135deg, #18191a 0%, #222426 30%, #1c1d1e 50%, #111212 80%, #0a0b0b 100%)",
    colors: ["Black"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Smooth Matte",
    colorGroup: "Deep Black",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "5.6 mm",
    visualLook: "Metal & Oxid Look",
    specificMaterialStyle: "Metal",
    productPhotoUrl: "https://media.grespania.com/productos/distrito_120x120_iron_web_list.webp"
  },
  {
    id: "jw02-washington-polished",
    name: "JW02 Washington JL 04 Polished 48x110",
    category: "Marble Look",
    finish: "Polished",
    formats: ["120×280cm"],
    specs: "Polished · 120×280 cm",
    origin: "Italy",
    veiningStyle: "Sweeping warm amber and soft ivory marble veins",
    description: "Classic high-contrast Calacatta marble design. A brilliant polished mirror face with majestic amber veining.",
    backgroundGradient: "linear-gradient(135deg, #e5dfd5 0%, #ffffff 40%, #d4c6b3 55%, #f2eae0 80%, #ffffff 100%)",
    colors: ["White"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Polished/High Gloss",
    colorGroup: "White & Cream",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "6 mm",
    visualLook: "Marble Look",
    specificMaterialStyle: "Calacatta Gold",
    productPhotoUrl: "https://media.grespania.com/productos/jw02_washington_polished_web_list.webp"
  },
  {
    id: "jw02-nero-marquinia-polished",
    name: "JW 02 Nero Marquinia JW 21 Polished 48x110",
    category: "Marble Look",
    finish: "Polished",
    formats: ["120×280cm"],
    specs: "Polished · 120×280 cm",
    origin: "Spain",
    veiningStyle: "Sharp ice-white lightning veins over pure obsidian black",
    description: "Striking black marble aesthetic with sharp geometric veins.",
    backgroundGradient: "linear-gradient(135deg, #0d0d0d 0%, #181818 40%, #ffffff 45%, #101010 50%, #080808 100%)",
    colors: ["Black"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Polished/High Gloss",
    colorGroup: "Deep Black",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "6 mm",
    visualLook: "Marble Look",
    specificMaterialStyle: "Nero Marquina",
    productPhotoUrl: "https://media.grespania.com/productos/jw21_nero_marquinia_polished_web_list.webp"
  },
  {
    id: "jw02-statuario-venato-polished",
    name: "JW02 Statuario Venato JW 14 Polished 48x110",
    category: "Marble Look",
    finish: "Polished",
    formats: ["120×280cm"],
    specs: "Polished · 120×280 cm",
    origin: "Italy",
    veiningStyle: "Interlocking rivers of ash-grey floating on pristine white",
    description: "The epitome of high-luxury Italian white marble, perfect for matching countertops and bathrooms.",
    backgroundGradient: "linear-gradient(135deg, #eeeeee 0%, #ffffff 40%, #a3a3a3 45%, #ffffff 50%, #f9f9f9 100%)",
    colors: ["White"],
    applications: ["Wall", "Floor"],
    finishAndFeel: "Polished/High Gloss",
    colorGroup: "White & Cream",
    sizeAndFormat: "Porcelain Slabs & Panels",
    thickness: "6 mm",
    visualLook: "Marble Look",
    specificMaterialStyle: "Statuario",
    productPhotoUrl: "https://media.grespania.com/productos/jw14_statuario_polished_web_list.webp"
  },
  {
    id: "calacatta-gold",
    name: "Calacatta Gold",
    category: "Marble Look",
    finish: "Polished",
    formats: ["160×320cm", "120×280cm", "120×120cm"],
    specs: "Polished · 160×320 cm",
    origin: "Fiorano Modenese, Italy",
    veiningStyle: "Dramatic warm gold and silver veining on an ivory canvas",
    description: "An iconic Italian marble look with sweeping ribbons of charcoal gray and rich amber-gold. Perfect for high-contrast waterfall islands and dramatic feature walls.",
    backgroundGradient: "linear-gradient(135deg, #161616 0%, #1e1d1a 40%, #2e261b 45%, #1d1d1d 50%, #181818 100%)",
    colors: ["White", "Beige"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "nero-marquina",
    name: "Nero Marquina",
    category: "Marble Look",
    finish: "Polished",
    formats: ["160×320cm", "120×280cm", "120×120cm"],
    specs: "Polished · 160×320 cm",
    origin: "Basque Country, Spain",
    veiningStyle: "Crisp, branching polar-white calcite veins over absolute obsidian",
    description: "Deepest black basalt aesthetic with striking crystalline white veins. Expresses a bold, graphic luxury in architectural powder rooms and sophisticated fireplace surrounds.",
    backgroundGradient: "linear-gradient(145deg, #090909 0%, #141414 45%, #5a5a5a 46%, #121212 48%, #0f0f0f 100%)",
    colors: ["Black"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "travertine",
    name: "Travertine",
    category: "Stone Look",
    finish: "Matte",
    formats: ["160×320cm", "120×120cm"],
    specs: "Matte · 160×320 cm",
    origin: "Tivoli, Italy",
    veiningStyle: "Stratified mineral ribbons of sand, cream, and warm greige",
    description: "A tribute to classical Roman architecture. Replicates the porous, linear sediment bands of natural thermal stone in a highly durable, low-maintenance porcelain format.",
    backgroundGradient: "linear-gradient(180deg, #1c1a17 0%, #29241e 30%, #201d19 60%, #1c1a17 100%)",
    colors: ["Beige", "Grey"],
    applications: ["Indoor", "Outdoor", "Floor", "Wall"]
  },
  {
    id: "statuario-extra",
    name: "Statuario Extra",
    category: "Marble Look",
    finish: "Polished",
    formats: ["160×320cm", "120×280cm", "120×120cm"],
    specs: "Polished · 160×320 cm",
    origin: "Carrara, Italy",
    veiningStyle: "Bold, wide slate-gray veins floating on an ultra-pure white ground",
    description: "The peak of classical marble elegance. Statuario Extra presents wide, expressive fluid-vein maps that add immediate luminosity and spatial weight to master suites.",
    backgroundGradient: "linear-gradient(135deg, #1b1b1b 0%, #252525 35%, #424242 40%, #1d1d1d 45%, #181818 100%)",
    colors: ["White"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "roma-imperial",
    name: "Roma Imperial",
    category: "Marble Look",
    finish: "Silk",
    formats: ["160×320cm", "120×280cm"],
    specs: "Silk · 160×320 cm",
    origin: "Brazil",
    veiningStyle: "Ethereal crystal networks of deep amber, rust, and sage blue",
    description: "A highly quartzite-inspired porcelain with deep mineral veins of copper, slate, and sapphire gold. Designed for clients seeking a bespoke, painting-like surface.",
    backgroundGradient: "linear-gradient(125deg, #18191a 0%, #26241f 40%, #3e3323 55%, #1e2124 100%)",
    colors: ["Beige", "Grey"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "frappuccino-marble",
    name: "Frappuccino",
    category: "Marble Look",
    finish: "Polished",
    formats: ["160×320cm", "120×120cm"],
    specs: "Polished · 160×320 cm",
    origin: "Italy",
    veiningStyle: "Intense, interlocking patterns of espresso, chocolate, and milk-cream",
    description: "An incredibly warm and luxurious surface rich in earthy movement. Broad, high-impact ripples of copper, mocha, and cream intertwine in a polished display.",
    backgroundGradient: "linear-gradient(155deg, #14110f 0%, #221d19 35%, #3d2f25 50%, #1e1916 70%, #14110f 100%)",
    colors: ["Black", "Beige"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "arabescato-orobico",
    name: "Arabescato Orobico",
    category: "Marble Look",
    finish: "Polished",
    formats: ["160×320cm", "120×280cm"],
    specs: "Polished · 160×320 cm",
    origin: "Bergamo, Italy",
    veiningStyle: "Sinuous, baroque waves of charcoal, steel gray, and bronze",
    description: "A highly dramatic stone characterized by swirling dark-gray and golden lines. Ideal for entry lobbies, reception desks, and bookmatched statement panels.",
    backgroundGradient: "linear-gradient(135deg, #111314 0%, #202426 35%, #3c3b31 55%, #191b1c 100%)",
    colors: ["Grey", "Black"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "concrete-series",
    name: "Concrete Series",
    category: "Concrete Look",
    finish: "Matte",
    formats: ["120×120cm", "120×280cm"],
    specs: "Matte · 120×280 cm",
    origin: "Spain",
    veiningStyle: "Minimalist, micro-cement textures with light industrial oxidation",
    description: "Understated urban luxury. A velvet-smooth tactile cement face with faint hand-troweled details. Brings clean modern restraint to minimalist indoor and outdoor living floors.",
    backgroundGradient: "linear-gradient(180deg, #191a1b 0%, #222426 50%, #191a1b 100%)",
    colors: ["Grey"],
    applications: ["Indoor", "Outdoor", "Floor", "Wall"]
  },
  {
    id: "quartzite-corteccia",
    name: "Quartzite Corteccia",
    category: "Stone Look",
    finish: "Silk",
    formats: ["160×320cm", "120×280cm"],
    specs: "Silk · 160×320 cm",
    origin: "Brazil",
    veiningStyle: "Linear crystalline striations of silver-gray and copper gold",
    description: "Recalls the organic geometry of ancient tree bark frozen in quartzite crystal. A sophisticated, neutral slab that commands attention under spotlighting.",
    backgroundGradient: "linear-gradient(120deg, #151717 0%, #242928 45%, #3a3225 60%, #151717 100%)",
    colors: ["Grey", "Beige"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "patagonie",
    name: "Patagonie",
    category: "Stone Look",
    finish: "Polished",
    formats: ["160×320cm"],
    specs: "Polished · 160×320 cm",
    origin: "Patagonia, Argentina",
    veiningStyle: "Fascinating clusters of translucent amber, obsidian quartz, and bone-white feldspar",
    description: "A hyper-luxury surface that replicates Patagonia quartzite's wild clastic clusters. Can be backlit to create a glowing, theatrical spatial crown.",
    backgroundGradient: "linear-gradient(135deg, #1c1c1a 0%, #2a2924 35%, #473e2d 55%, #242629 75%, #1c1c1a 100%)",
    colors: ["White", "Beige"],
    applications: ["Indoor", "Wall"]
  },
  {
    id: "dual-white",
    name: "Dual White",
    category: "Concrete Look",
    finish: "Matte",
    formats: ["160×320cm", "120×120cm"],
    specs: "Matte · 160×320 cm",
    origin: "Spain",
    veiningStyle: "Absolute, flawless matte snow-white with zero impurity",
    description: "Pure, architectural light. Dual White provides a monolithic, seamless white surface that reflects daylight beautifully without glare. The ultimate choice for ultra-modern villas.",
    backgroundGradient: "linear-gradient(135deg, #222222 0%, #303030 50%, #222222 100%)",
    colors: ["White"],
    applications: ["Indoor", "Outdoor", "Floor", "Wall"]
  },
  {
    id: "nature-mood-rainforest",
    name: "Nature Mood (Rainforest)",
    category: "Stone Look",
    finish: "Silk",
    formats: ["160×320cm", "120×280cm"],
    specs: "Silk · 160×320 cm",
    origin: "Italy",
    veiningStyle: "Biophilic networks of deep olive green, walnut brown, and golden clay",
    description: "Part of the Nature Mood series. Captures the deep, serene color combinations of dense forests and wet clay, blending interior spaces with the calming presence of nature.",
    backgroundGradient: "linear-gradient(135deg, #0e110f 0%, #171d18 45%, #2c251a 60%, #0e110f 100%)",
    colors: ["Beige"],
    applications: ["Indoor", "Floor", "Wall"]
  },
  {
    id: "nature-mood-mountain-peak",
    name: "Nature Mood (Mountain Peak)",
    category: "Stone Look",
    finish: "Matte",
    formats: ["160×320cm", "120×280cm"],
    specs: "Matte · 160×320 cm",
    origin: "Italy",
    veiningStyle: "High-altitude slate grey with fractured white alpine veins",
    description: "A dramatic grey surface that captures the raw power of rocky high-altitude ridges. Offers outstanding textural grip and physical presence for wellness and wet applications.",
    backgroundGradient: "linear-gradient(145deg, #141617 0%, #1f2326 50%, #303233 55%, #141617 100%)",
    colors: ["Grey"],
    applications: ["Indoor", "Outdoor", "Floor", "Wall"]
  },
  {
    id: "nature-mood-riverbed",
    name: "Nature Mood (Riverbed)",
    category: "Stone Look",
    finish: "Textured",
    formats: ["160×320cm", "120×120cm"],
    specs: "Textured · 160×320 cm",
    origin: "Italy",
    veiningStyle: "Water-polished pebbles, slate silt, and river-sand deposits",
    description: "A unique organic stone texture mimicking ancient alluvial deposits. Highly slip-resistant, perfect for premium outdoor poolside decks and luxury spa floors.",
    backgroundGradient: "linear-gradient(180deg, #191816 0%, #29241f 50%, #191816 100%)",
    colors: ["Grey", "Beige"],
    applications: ["Outdoor", "Floor"]
  },
  {
    id: "distrito-iron",
    name: "Distrito (Iron)",
    category: "Metal Look",
    finish: "Textured",
    formats: ["160×320cm", "120×280cm"],
    specs: "Metallic · 160×320 cm",
    origin: "Spain",
    veiningStyle: "Corten steel rust-hues, deep oxides, and dark charcoal cast-iron",
    description: "An industrial-chic masterpiece. Captures the architectural oxidation of cast iron and weathered alloy plates. Adds instant character to loft walls and exterior claddings.",
    backgroundGradient: "linear-gradient(135deg, #151312 0%, #261f1b 45%, #3c2a1e 55%, #1c1816 70%, #151312 100%)",
    colors: ["Black", "Grey"],
    applications: ["Indoor", "Outdoor", "Wall"]
  },
  {
    id: "ankara-bronze",
    name: "Ankara Bronze",
    category: "Metal Look",
    finish: "Silk",
    formats: ["160×320cm"],
    specs: "Silk · 160×320 cm",
    origin: "Turkey",
    veiningStyle: "Deep burnished bronze base with thread-thin rose-gold veins",
    description: "Warm, highly polished metallic bronze. Combines dark coppery tones with subtle rose-gold crystalline veins to create a fireplace or back-panel focal point of incredible luxury.",
    backgroundGradient: "linear-gradient(135deg, #131110 0%, #221d1a 40%, #3b2d22 55%, #181514 100%)",
    colors: ["Black", "Beige"],
    applications: ["Indoor", "Wall"]
  },
  {
    id: "arken-gris",
    name: "Arken Gris",
    category: "Concrete Look",
    finish: "Matte",
    formats: ["120×120cm", "48×108cm"],
    specs: "Matte · 120×120 cm",
    origin: "Spain",
    veiningStyle: "Clean volcanic ash gray with micro-quartz inclusions",
    description: "A highly versatile, basaltic slate look. Extremely popular in modern architectural villas, providing a seamless indoor-to-outdoor continuous floor flow with immense durability.",
    backgroundGradient: "linear-gradient(145deg, #131415 0%, #202224 50%, #131415 100%)",
    colors: ["Grey"],
    applications: ["Indoor", "Outdoor", "Floor", "Wall"]
  }
];

export const APPLICATION_TILES = [
  {
    id: "residential",
    title: "Residential",
    tagline: "Private Villas & Estates",
    gradient: "linear-gradient(to top, rgba(10,10,10,0.95) 0%, rgba(10,10,10,0.4) 60%, rgba(10,10,10,0) 100%), linear-gradient(135deg, #18191b 0%, #262a2e 100%)",
    description: "Elevating daily living into a sensory experience. Custom marble bookmatches, seamless large-format bathrooms, and culinary islands."
  },
  {
    id: "commercial",
    title: "Commercial",
    tagline: "High-Traffic Grandeur",
    gradient: "linear-gradient(to top, rgba(10,10,10,0.95) 0%, rgba(10,10,10,0.4) 60%, rgba(10,10,10,0) 100%), linear-gradient(145deg, #111111 0%, #232323 100%)",
    description: "Unyielding technical durability meets editorial design. Monumental reception lobbies, boutique offices, and luxury corridors."
  },
  {
    id: "hospitality",
    title: "Hospitality",
    tagline: "Unforgettable Venues",
    gradient: "linear-gradient(to top, rgba(10,10,10,0.95) 0%, rgba(10,10,10,0.4) 60%, rgba(10,10,10,0) 100%), linear-gradient(125deg, #151310 0%, #2c251f 100%)",
    description: "Crafting atmospheric spaces of travel and leisure. High-end restaurants, signature hotel wet rooms, and premium spa retreats."
  },
  {
    id: "outdoor",
    title: "Outdoor",
    tagline: "Open-Air Architecture",
    gradient: "linear-gradient(to top, rgba(10,10,10,0.95) 0%, rgba(10,10,10,0.4) 60%, rgba(10,10,10,0) 100%), linear-gradient(180deg, #1c1a17 0%, #151413 100%)",
    description: "Slip-resistant, frost-proof monolithic decks and pool surrounds that frame the Florida sun without fading or wear."
  }
];

export const PROJECT_CARDS = [
  {
    id: "proj-1",
    title: "Lake Nona Mansion",
    location: "Orlando, FL",
    material: "Calacatta Gold Floor & Slabs",
    type: "Residential Interior"
  },
  {
    id: "proj-2",
    title: "Winter Park Estate",
    location: "Orlando, FL",
    material: "Nero Marquina Fireplace & Cladding",
    type: "Residential Master Suite"
  },
  {
    id: "proj-3",
    title: "Windermere Retreat",
    location: "Orlando, FL",
    material: "Travertine Deck & Pools",
    type: "Outdoor Living Space"
  },
  {
    id: "proj-4",
    title: "Dr. Phillips Penthouse",
    location: "Orlando, FL",
    material: "Statuario Extra Kitchen Island",
    type: "Residential Penthouse"
  },
  {
    id: "proj-5",
    title: "Downtown Hospitality Hub",
    location: "Orlando, FL",
    material: "Concrete Series Grand Lobby",
    type: "Hotel Ingress & Lounge"
  },
  {
    id: "proj-6",
    title: "Aria Luxury Showroom",
    location: "Miami, FL",
    material: "Roma Imperial Statement Slabs",
    type: "High-End Corporate Boutique"
  }
];
